lttng-modules: update to 2.11.2
Upgrade to version 2.11.2 in order to fix some build errors
with latest 5.4 kernel.

- conflicting types for 'trace_fast_page_fault'
Reproductible on kernel greater than v5.4.19, starting with commit
8a1cd01bee ("KVM: x86: Use gpa_t for cr2/gpa to fix TDP support on
32-bit KVM")

Error messages:
lttng-modules-2.11.1/probes/../probes/lttng-tracepoint-event-impl.h:130:6:
error:
  130 | void trace_##_name(_proto);
tmp/work-shared/axxiax86-64/kernel-source/include/linux/tracepoint.h:233:21:
note: previous definition of 'trace_fast_page_fault' was here
  233 |  static inline void trace_##name(proto)

- conflicting types for 'trace_rcu_dyntick'
Reproductible on kernel greater than v5.4.22, starting with commit
6cf539a87a ("rcu: Fix data-race due to atomic_t copy-by-value")

Error messages:
lttng-modules-2.11.1/probes/../probes/lttng-tracepoint-event-impl.h:130:6:
error: conflicting types for 'trace_rcu_dyntick'
  130 | void trace_##_name
tmp/work-shared/axxiax86-64/kernel-source/include/linux/tracepoint.h:233:21:
note: previous definition of 'trace_rcu_dyntick' was here
  233 |  static inline void trace_##name(proto)

Signed-off-by: Daniel Dragomir <Daniel.Dragomir@windriver.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>